version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers-legacy
    steps:
      - checkout
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: pip install -r services/users/requirements-dev.txt
